MAKAIA-2814 apply feedback
MakairaIO/oxid-connect-essential pull request #9
Opened 2022-06-22 11:06 UTC by kyoya-de

- feat: Change namespace for event class
- feat: Fail GH action run if tests fail
- feat: Add PHP 8.1 to build process

2022-06-24 07:56 UTC, duongnfq841992 requested changes

2022-06-24 07:56 UTC, duongnfq841992 commented on src/Service/TrackingRenderService.php
> +
```suggestion

    /**
     * @throws EmptyTrackingDataException
     * @throws NoArticleException
     * @throws ArticleInputException
     */
```

2022-06-24 07:56 UTC, duongnfq841992 commented on src/Modifier/Product/VariantAttributesModifier.php
> +                    $variantAttributes[$hash] = (float) $value;
I think this block and the block above(line 134->141) is solving a same issue so I suggest you to create a function for this :smile:

2022-06-24 08:05 UTC, kyoya-de commented on src/Modifier/Product/VariantAttributesModifier.php
> +                    $variantAttributes[$hash] = (float) $value;
I won't change it now, because it's very important part of the filtering and I won't break it.

2022-06-29 04:34 UTC, duongnfq841992 approved these changes

2022-06-29 12:38 UTC, merged

2022-06-29 12:42 UTC, makaira-github commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/MakairaIO/oxid-connect-essential/releases/tag/1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: